# kind: Ingress
# apiVersion: networking.k8s.io/v1
# metadata:
#   name: ingress
# spec:
#   rules:
#     - host: {{ .Values.route.host }}
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: {{ .Chart.Name }}
#                 port:
#                   number: {{ .Values.service.port }}